### ISSUE TITLE
How to send nmea0183 using this plugin?

### ISSUE THREAD

**Issue by ignamendi21** [SignalK/signalk-to-nmea0183#107]
Hello,
I want to send nmea0183 data using signalk and using this plugin. I read this and I think this is just what I need, however I still do not know how to actually send something back trought my serial connection.

I have bidirection rs232/483 connection and I can read, now I want to write.

I have install this plugin, now I want to send a value for the HSC pgn for example...

What would be the end 2 end steps!?

Thanks in advance!

**Comment by tkurki** [comment]
See https://github.com/SignalK/signalk-server/wiki/Events-and-Outputting-Data

**Comment by ignamendi21** [comment]
> See https://github.com/SignalK/signalk-server/wiki/Events-and-Outputting-Data

thanks for your answer. 
I have looked at it, but I am still lost. 
Could you give me some more guidance on it?
Thanks in advance!

**Comment by tkurki** [comment]
>if you want to direct the output of the signalk-to-nmea0183 plugin into a serial connection you enter nmea0183out in the Output events field.

**Comment by ignamendi21** [comment]
> > if you want to direct the output of the signalk-to-nmea0183 plugin into a serial connection you enter nmea0183out in the Output events field.

Thanks tkurki

Now I have a question. 
I am reading nmea0183 that I can see in my signalk datas. Now what I want is to modify some if this values and send them back to the nmea 0183 network. 

Do you understand me?

Do you know the signalk/autopilot plugin used to control raymarine autopilots? I have used it, and I imagine this is how it works... What I want is to replicate this but for a NMEA0183 network

**Comment by tkurki** [comment]
Autopilot plugin generates NMEA 2000 and Seatalk 1 messages (encapsulated 0183) when you press the button. You can not do similar things over normal NMEA 0183.
