### ISSUE TITLE
Update documentation to include reference to default TCP output on 10110

### ISSUE THREAD

**Issue by GaryWSmith** [SignalK/signalk-to-nmea0183#37]
A slightly modified README.md doc with reference to the default TCP output and clarifying the required changes to settings.json file
[README.zip](https://github.com/SignalK/signalk-to-nmea0183/files/3423558/README.zip)

**Comment by sbender9** [comment]
Do you know how to do a Pull Request? That would be the appropriate way of submitting changes.

**Comment by GaryWSmith** [comment]
Being new at this I followed the github guide but it doesn't appear as if I am authorised to create a new branch in order to fulfill the pull request.

**Comment by sbender9** [comment]
You need to create your own fork and do the work there. Then you can submit a PR to this repository.

**Comment by sbender9** [comment]
Here’s some more info and some guidelines: https://github.com/SignalK/signalk-server-node/blob/master/docs/CONTRIBUTING.md

**Comment by GaryWSmith** [comment]
ok, great thanks.
