### ISSUE TITLE
GPS not received by Navionics Boating app

### ISSUE THREAD

**Issue by bhavers** [SignalK/signalk-to-nmea0183#41]
Many apps receive the GPS location, but the Navionics Boating app doesn't.
When i look at the data (source are sample files from /opt/signalk-server/samples/) i see sentences with an $II prefix instead of $GP, for example:

$IIGGA,190048,5943.4074,N,02444.1567,E,1,11,0.8,2.26,M,0,M,,*4E
$IIGLL,5943.4074,N,02444.1567,E,210048.020,A*21
$IIRMC,190048,A,5943.4074,N,02444.1567,E,6.7,187.3,150814,8.1,E*66

That doesn't seem to work for Navionics. If i use the standart gps.log sample (/opt/signalk-server/samples/), for some reason the output also includes $GP prefixed sentenced. And that does work, see example below.

$GPGGA,085609.000,5222.3257,N,00454.5851,E,1,6,1.18,15.1,M,47.0,M,,*6E
$IIGGA,085608,5222.3257,N,00454.5851,E,1,6,1,15,M,0,M,,*73
$IIGLL,5222.3257,N,00454.5851,E,105608.020,A*23
$IIRMC,085608,A,5222.3257,N,00454.5851,E,0.8,248.0,030414,0.0,E*6E
$GPGSA,A,3,02,16,23,13,29,07,,,,,,,1.48,1.18,0.89*0C
$GPRMC,085609.000,A,5222.3257,N,00454.5851,E,0.81,248.69,030414,,,A*6E

Questions:
- in the source i see that signalk-to-nmea0183 is creating these $II prefixed sentences, why is that?
I do see that Shipmodul can do the same, so i guess the prefix shouldn't matter for the consuming app: http://www.shipmodul.com/downloads/manuals/legacy/miniplex-42.pdf, page 9 Talker ID

- If this is according to the standard, than still widely used apps like Navionics can not use this. Would it be possible to make this configurable? Similar to how Shipmodul is doing this for example? Or just a switch to use either $II or $GP?

**Comment by cmotelet** [comment]
By the PR #35, a few months ago, we chose to use $II (Integrated Instrumentation) as talkerId rather than $SK for NMEA sentences to extend compatibility.
Apparently this is not enough to cover all softwares.
In a few days, we will add in the plugin settings the possibility to choose the talkerId for each sentence.

**Comment by bhavers** [comment]
Great, looking forward to it, thanks!

**Comment by bhavers** [comment]
just fyi
Navionics support replied back that their Navionics Boating app expects $GPRMC for location.

**Comment by cmotelet** [comment]
Thank you, I'm working on it.
I will set $GP by default to GGA, RMC & GLL.
All talkerIDs will be configurable.

**Comment by cmotelet** [comment]
You can update to version 1.6.0.
This should solve your problem.
In a future version the talkersID will be configurable. This is not yet easily done at the moment (https://github.com/SignalK/signalk-server-node/pull/871)
You can close the issue if it is OK for you.

**Comment by bhavers** [comment]
Tested it, but it still does not work with the Navionics Boating. In the output i see that your changes have worked, but that the Boating app is still reporting that it doesn't receive a location. I will contact Navionics support and get back on this.

Output from signalk-to-nmea0183:
$IIMWV,309,T,05.50,N,A*2F
$IIVWT,051,L,05.50,N,02.83,M,,*27
$IIHDT,,T*0C
$GPWCV,,N,,D*5F
$GPXTE,A,A,,R,N,D*06
$GPZDA,105021,,,,00,*4F
$IIDBT,065.84,f,020.07,M,010.84,F*26
$GPGLL,6000.284,N,02327.741,E,105021,A,D*4B
$GPRMC,,A,6000.2840,N,02327.7410,E,5.0,207.1,,,E*57

Two other things i noticed, should i open separate issues for this?

1. Even though i only select the plugin to publish the RMC sentence, it still published other sentences as well

2. When you upgrade the plugin through the web interface the following message is shown: "Installed This Session (restart required)". When Signalk is restarted (with the button in de web interface) this message does not disappear.

**Comment by tkurki** [comment]
Don't know if it matters, but your system is missing date & time information and magnetic variation and those fields are empty in  the RMC output.

**Comment by bhavers** [comment]
As i am at home now i am replaying a sample data file (plaka.log). That works with apps like iNavx and iSailor but not with Navionics. The Navionics app might expect more data, hope that their support will be able to tell what they need as a minimum ( i have send them an email with this question).

**Comment by cmotelet** [comment]
Here are some tips and questions:
- in your flow, I see ZDA and XTE. The talkerID for these 2 sentences should be $II (that's what the plugin produces) and in yours I see $GP. Are you sure you don't have any other plugins enabled?
- You can try to activate GGA, I remember a software that needed this sentence to work even if it was not specified in the documentation.
- I just tested on my server and if I only enable RMC I only have RMC in my TCP stream on port 10110.
- And as @tkurki says, the time and date are missing in your RMC sentences.
- Are you really sure that these sentences come from your signalK server ?
- what type of flow do you use TCP or UDP

**Comment by cmotelet** [comment]
try to replay `aava-n2k.data` in your signalk-server-node instead of `plaka.log`.

**Comment by bhavers** [comment]
I have all plugins disabled. But i just noticed that even the with the nmea0183 plugin disabled it is still publishing data on port 10110. I did a bit of experimentation with udp on port 2000 as well and i see that Navionics automatically sees that as the standard configured build-in Digital Yacht WLN10 devices (but it doesn't work either, no gps data).
So now i am unstalling all plugins to be sure. Is it correct if i do npm uninstall <package> in the /home/pi/.signalk/node_modules directory?

As not all modules are in that directory, some are in /opt/signalk-server/node_modules. 

I will try aava-n2k.data as well

**Comment by bhavers** [comment]
aava-n2k.data works indeed.
Now the filter also seems to work because i only receive RMC sentences

$GPRMC,190119,A,5943.3540,N,02444.1374,E,6.1,193.5,150814,8.1,E*70
$GPRMC,190119,A,5943.3523,N,02444.1365,E,6.1,196.5,150814,8.1,E*70
$GPRMC,190120,A,5943.3523,N,02444.1365,E,6.1,196.5,150814,8.1,E*7A

An if i enabled some other sentences it works as well (not sure why this doesn't seem to work with plaka.log, maybe i changed some other things as well).

$IIDBT,63.4,f,19.33,M,10.6,F*1F
$GPGGA,190425,5943.0179,N,02443.9359,E,1,10,0.8,0.01,M,0,M,,*5C
$GPGLL,5943.0179,N,02443.9359,E,210425.020,A*35
$GPRMC,190425,A,5943.0179,N,02443.9359,E,6.7,204.8,150814,8.1,E*71

**Comment by cmotelet** [comment]
And Navionics app too ?

**Comment by bhavers** [comment]
Yes, this works in Navionics too.

**Comment by bhavers** [comment]
Thanks for your help, think we can close this issue.

**Comment by tkurki** [comment]
Just so you know how things work: **all** the server's NMEA0183 data is available over tcp 10110. So if your original input is NMEA0183, like when using plaka.log `--sample-nmea0183-data`, you will get the input data on 10110 with no plugins involved.

So there is no filtering involved.

**Comment by bhavers** [comment]
Wasn't aware of that, thanks for clarifying.

**Comment by bhavers** [comment]
FYI i received a response from Navionics on this as well, that the received data is incomplete:

Quote from Navionics:

> Unfortunately our NMEA decoder considers an error the fact that he cannot receive a valid UTC date. 
> In fact, if you see the NMEA data you've sent me, you can see that the NMEA sentence $GPZDA,105021,,,,00,4F has not a date.
