### ISSUE TITLE
Not all sentences passed to Serial O/P

### ISSUE THREAD

**Issue by benwingrove** [SignalK/signalk-to-nmea0183#55]
Via TCP I am receiving the following sentences
GGA,GLL,RMC,DBK,DBS,DBT,HDG,HDM,HDT,MTW,MWD,MWV,VHW,VWR,VWT,ZDA

Via Serial output I am only receiving the following, all the output types are ticked in the plugin config.
GGA,GLL,RMC,HDG,HDM,HDT

Server v1.35.2 Plugin v1.7.1

**Comment by tkurki** [comment]
I don't think this is a plugin issue per your email message. Closing, if I'm wrong we can reopen the issue.
