### ISSUE TITLE
Plug-in Running when Disabled in Settings

### ISSUE THREAD

**Issue by twotwisted** [SignalK/signalk-to-nmea0183#58]
The Plug-in is installed by default and even though in plugin settings with it disabled it appears to be running anyway.

**Comment by tkurki** [comment]
Is the plugin enabled in the plugin configuration UI after server restart?

How do you know that it is running?

If you active the debug key `signalk-server:events:nmea0183out` in the Server log do you see nmea0183 data generated?

**Comment by twotwisted** [comment]
No, it is disabled after a restart. Yet, I can connect to it via 10110.

Yes nmea0183 is in log.

![Screenshot 2020-11-10 090452](https://user-images.githubusercontent.com/29116227/98602994-75b58000-2335-11eb-8ead-05e0deaf2261.png)
![Screenshot_20201110-090623_Boating HD](https://user-images.githubusercontent.com/29116227/98602998-76e6ad00-2335-11eb-9fad-451000ba9248.jpg)
![Screenshot_20201110-090635_Boating HD](https://user-images.githubusercontent.com/29116227/98603000-777f4380-2335-11eb-815e-1b7b0eaf615a.jpg)

**Comment by tkurki** [comment]
I think you are confusing the fact that the port 10110 is open (and data is available there) with the plugin's operation.

The port is open by default and is not controlled by the plugin. If your system has any NMEA0183 input it will be available on 10110.

If you want to disable the 10110 port it is `nmea-tcp` in Server / Settings

![image](https://user-images.githubusercontent.com/1049678/98643048-17899c80-2337-11eb-82e7-d13b11ca5abf.png)


The plugin is involved if you have non NMEA0183, like NMEA2000 data that is converted to Signal K and then you'd want this data to be converted to NMEA0183 data. For example I have NMEA2000 plotter and my DSC VHF needs position in NMEA0183, so I have enabled the plugin and relevant sentences there.

**Comment by twotwisted** [comment]
Thank you so much for clarifying! Signalk is a fantastic project, even if you don't need Signalk data, however the documentation for Signalk and some plugins needs to be improved.

**Comment by tkurki** [comment]
I agree on the documentation, but it would absolutely wonderful if other people than the main developers (who are way too far in to see what's unclear) could help in documenting.
