### ISSUE TITLE
Missing VHW NMEA183 sentence with speed through water

### ISSUE THREAD

**Issue by olewsaa** [SignalK/signalk-to-nmea0183#72]
I do not get speed through water in OpenCPN when running the SignalK to NMEA183 converter. Most other data is OK. I'm using the converter to feed the Polar diagram recorder (also tested VDR, which works ok, but no STW). The speedThroughWater signalK works fine, display nicely on the instrument panel web app and OpenCPN dashboard. I do not find a tick box for VHW on the plugin config, but the file VHW.js exists and there is a reference to speedThroughWater in that file. I have also redirected the NMEA183 sentences to a file and searched for VHW without finding any. 

It would be nice to have the Polar diagram based on speed though water in addition to speed over ground reference. Any possible fix for this ?

**Comment by tkurki** [comment]
It's there in demo.signalk.org. Are you absolutely sure it is missing?

(demo.signalk.org is behind authentication, so plugin config is not publicly accessible on purpose)

![image](https://user-images.githubusercontent.com/1049678/120974549-ef510780-c778-11eb-90b5-4d906219fd13.png)

**Comment by olewsaa** [comment]
I have looked for it, but as the system is onboard and not here at home I cannot do it again. Did it undergo upgrades or additions lately ? Maybe I have a slightly older version. My versions seems to have the same as the figure in the git readme.  The RPi onboard is not normally connected to the internet, only some time to time for upgrades etc.

**Comment by sticky-booger** [comment]
I had the same issue but manage to solve it.
You need all the data that a VHW message is supposed to send in signal-k otherwise it wont work, I was missing true heading data.
I have a B&G ZG100 and it's not sending true heading but it does send magnetic and magnetic variation at least according to the signal-k data browser.

/**
$IIVHW,x .x,T,x.x,M,x.x,N,x.x,K*hh
       I I I I I I I__I_Surface speed in kph
       I I I I I__I_Surface speed in knots
       I I I__I_Magnetic compass heading
       I__I_True compass heading
 */

I solved it by installing the plugin signalk-derived-data and under the Heading menu activate..
True Heading (based on magnetic heading and magneticVarition)

**Comment by thompero** [comment]
Even if the VHW is activaded in the tick box it is not present at serial interface.
I'm using a Raspery with Pican-M to send nmea183 via serial port using Signalk Simulator. Most nmea sentenses are ok but not VHW (water speed and heading). E.g MWV, MWT, DBT and HDT are all ok. These I have in seriel inteface, tcp and Signalk Databrowser.
The VHW values are present in the Signalk Databrowser but not in serial interface or tcp (using putty).
Both Raspberry (Buster) and Signalk (v16.19.0, 9.2.0) were updated last week.

**Comment by tkurki** [comment]
VHW output requires these three data: https://github.com/SignalK/signalk-to-nmea0183/blob/master/sentences/VHW.js#L17

are they present in your data?

**Comment by thompero** [comment]
Nice with a fast answer :)
I have checked my file and it has exactly the same content. I also have put the file You refered to in the directory instead of the original one and still the same result – no VHW at serial out.

**Comment by tkurki** [comment]
Not what i meant. Check in DataBrowser that you have all those three paths with data.

**Comment by thompero** [comment]
To fast solution!
The VHW is present at serial out but of course with wrong content. Is there a way to have the "Magnetic variation" from the Simulator? Any fix in some Simulator file?

**Comment by tkurki** [comment]
The order of the paths in the array correspond to the parameters of the function that follows https://github.com/SignalK/signalk-server/wiki/FAQ:-Frequently-Asked-Questions#how-to-add-missing-units-and-static-data-eg-displayname
so commenting paths out will put the values in the wrong parameter.

But modifying the source code manually is anyway a poor way to do this, as it will get overwritten when updating to a future version and won't be there if you need to reinstall.

But https://github.com/SignalK/signalk-server/wiki/FAQ:-Frequently-Asked-Questions#how-to-add-missing-units-and-static-data-eg-displayname has instructions for adding missing (static) data, that would persist over signalk-to-nmea0183 updates and should be copied over to a new system if you need to reinstall.
