### ISSUE TITLE
Support Questions

### ISSUE THREAD

**Issue by Wardy1279** [SignalK/signalk-to-nmea0183#95]
Hi,

I don't use GitHub very often so I'd appreciate any advice on where to post questions like the following!

**A Bit Of Background:**

I would like n2k-to-signalk to send the 129029 PGN to signalk-to-nmea0183 and output GGA and ZDA to my laptop (which reads incoming messages) via USB.
I know this can be done by a regular converter like the NGW-1, but my intention is to familiarise myself with SignalK so that I can create the plugin to convert the 128520 PGN to the TTM sentence in the future, as to the best of my knowledge this is not supported at the moment.

**My Questions:**

1. I have been using the sample n2k messages and I can see them coming in on the signalk dashboard, but how do I know if they are being converted to the signalk format? 
2. Once the n2k messages are converted to the signalk format, how do I setup signalk-to-nmea0183 to convert these to NMEA 0183 and transmit these to the USB port?
3. Any advice for how to approach the custom plugin?

Thanks in advance!

**Comment by tkurki** [comment]
Don't know how you ended posting this here. I just reorganised signalk.org a bit to make Discussions and Slack links more prominent, please continue in either one.

Short answers:
- n2k-signalk converts from nmea2000 to signalk. 129029 is supported, 128520 is not completely reverse engineered per https://canboat.github.io/canboat/canboat.xml (where nmea2000 decoding comes from)
- Data Browser shows Signal K data, so if you see it there it is being converted. And conversely: if it is not there it is not converted

No need to create a custom plugin, but once 128520 is converted to Signal K add support for converting to TTM in this plugin.

See also https://github.com/SignalK/signalk-server/wiki/FAQ:-Frequently-Asked-Questions

Now reading your questions: do you have signalk-server running? These components and plugins are used in the server and configuring serial output is done in the server ui.

Closing, Slack is your best bet for getting support from peer users.

**Comment by Wardy1279** [comment]
Thanks for your support! 

I will redirect future questions to Slack.

Cameron.
